AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  AwsAccessKeyId:
    Type: String
  AwsRegion:
    Type: String
    Default: ap-south-1
  AwsSecretAccessKey:
    Type: String
  S3BucketName:
    Type: String
  HrEmail:
    Type: String
  AdminEmail:
    Type: String
  DbHost:
    Type: String
  DbName:
    Type: String
  DbPassword:
    Type: String
  DbUser:
    Type: String
  EmailHost:
    Type: String
  EmailPass:
    Type: String
  EmailPort:
    Type: Number
  EmailSecure:
    Type: String
  EmailUser:
    Type: String
  JwtSecret:
    Type: String
  CareerEmail:
    Type: String
  ContactEmail:
    Type: String
  HrmsAwsAccessKeyId:
    Type: String
  HrmsAwsSecretAccessKey:
    Type: String
  HrmsAwsRegion:
    Type: String
  HrmsBucketUrl:
    Type: String
  HrmsDbHost:
    Type: String
  HrmsDbName:
    Type: String
  HrmsDbPassword:
    Type: String
  HrmsDbUser:
    Type: String
  HrmsS3BucketName:
    Type: String
  HrEmailPass:
    Type: String
  StackName:
    Type: String
    Description: Name of the CloudFormation stack
    Default: firsttracksolutiontechnologies-backend

Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: api

  AppFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.handler
      Runtime: nodejs20.x
      MemorySize: 512
      Timeout: 30
      Environment:
        Variables:
          AWS_ACCESS_KEY_ID_: !Ref AwsAccessKeyId
          AWS_REGION_: !Ref AwsRegion
          AWS_SECRET_ACCESS_KEY_: !Ref AwsSecretAccessKey
          S3_BUCKET_NAME_: !Ref S3BucketName
          HR_EMAIL: !Ref HrEmail
          ADMIN_EMAIL: !Ref AdminEmail
          DB_HOST: !Ref DbHost
          DB_NAME: !Ref DbName
          DB_PASSWORD: !Ref DbPassword
          DB_USER: !Ref DbUser
          EMAIL_HOST: !Ref EmailHost
          EMAIL_PASS: !Ref EmailPass
          EMAIL_PORT: !Ref EmailPort
          EMAIL_SECURE: !Ref EmailSecure
          EMAIL_USER: !Ref EmailUser
          JWT_SECRET: !Ref JwtSecret
      Events:
        ProxyApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /{proxy+}
            Method: ANY

Outputs:
  AppFunctionArn:
    Description: Lambda Function ARN
    Value:
      Fn::GetAtt:
        - AppFunction
        - Arn
  ApiUrl:
    Description: API Gateway endpoint URL
    Value:
      Fn::Sub: https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/api/
