name: Build and Deploy SAM Application

on:
  push:
    branches:
      - master # Trigger on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID_ }}
          aws-secret-access-key: ${{ vars.AWS_SECRET_ACCESS_KEY_ }}
          aws-region: ap-south-1

      - name: Install SAM CLI
        run: |
          pip install aws-sam-cli

      - name: Build SAM Application
        run: |
          sam build

      - name: Deploy SAM Application
        run: |
          sam deploy \
            --stack-name firsttracksolutiontechnologies-backend \
            --s3-bucket firsttracksolutiontechnologies-backend-sam \
            --capabilities CAPABILITY_IAM \
            --parameter-overrides \
              AwsAccessKeyId=${{ vars.AWS_ACCESS_KEY_ID_ }} \
              AwsRegion=ap-south-1 \
              AwsSecretAccessKey=${{ vars.AWS_SECRET_ACCESS_KEY_ }} \
              S3BucketName=${{ vars.S3_BUCKET_NAME_ }} \
              HrEmail=${{ vars.HR_EMAIL }} \
              AdminEmail=${{ vars.ADMIN_EMAIL }} \
              DbHost=${{ vars.DB_HOST }} \
              DbName=${{ vars.DB_NAME }} \
              DbPassword=${{ vars.DB_PASSWORD }} \
              DbUser=${{ vars.DB_USER }} \
              EmailHost=${{ vars.EMAIL_HOST }} \
              EmailPass=${{ vars.EMAIL_PASS }} \
              EmailPort=${{ vars.EMAIL_PORT }} \
              EmailSecure=${{ vars.EMAIL_SECURE }} \
              EmailUser=${{ vars.EMAIL_USER }} \
              JwtSecret=${{ vars.JWT_SECRET }} \
              CareerEmail=${{ vars.CAREER_EMAIL }} \
              ContactEmail=${{ vars.CONTACT_EMAIL }} \
              HrmsAwsAccessKeyId=${{ vars.HRMS_AWS_ACCESS_KEY_ID_ }} \
              HrmsAwsSecretAccessKey=${{ vars.HRMS_AWS_SECRET_ACCESS_KEY_ }} \
              HrmsAwsRegion=${{ vars.HRMS_AWS_REGION_ }} \
              HrmsBucketUrl=${{ vars.HRMS_BUCKET_URL }} \
              HrmsDbHost=${{ vars.HRMS_DB_HOST }} \
              HrmsDbName=${{ vars.HRMS_DB_NAME }} \
              HrmsDbPassword=${{ vars.HRMS_DB_PASSWORD }} \
              HrmsDbUser=${{ vars.HRMS_DB_USER }} \
              HrmsS3BucketName=${{ vars.HRMS_S3_BUCKET_NAME_ }} \
              HrEmailPass=${{ vars.HR_EMAIL_PASS }}
